substitutions:
  device: boiler
  name: "Frisquet Boiler"
  reboot_timeout: 14d
  update_interval: 60s
  ota_password: "86d8d705bb585eaf7a68c592a025884c"

esphome:
  name: ${device}

preferences:
  flash_write_interval: 1h

external_components:
  - source: github://philippemezzadri/frisquet-esphome
  
esp32:
  board: esp32dev
  framework:
    type: arduino

packages:
  common: !include common/common.yaml
  binary_sensors: !include common/binary_sensors.yaml
  sensors: !include common/sensors.yaml
  switches: !include common/switches.yaml
  text_sensors: !include common/text_sensors.yaml
  debug: !include common/debug.yaml

logger:
  baud_rate: 0
  level: DEBUG
  logs:
    sensor: INFO
    text_sensor: INFO

dallas:
  - pin: GPIO26

sensor:
  - platform: homeassistant
    id: current_temperature
    entity_id: sensor.living_room_temperature
    unit_of_measurement: "°C"
    filters:
      - filter_out: nan
      - heartbeat: 60s
        
  - platform: homeassistant
    id: outdoor_temperature
    entity_id: sensor.outdoor_temperature
    unit_of_measurement: "°C"
    filters:
      - filter_out: nan
      - heartbeat: 60s

  - platform: dallas
    address: 0xA2032131AB675C28
    name: "Boiler flow temperature"

  - platform: dallas
    address: 0xAB03213190136128
    name: "Boiler return temperature"

  - platform: heat_curve_climate
    name: "Boiler temperature setpoint"
    unit_of_measurement: "°C"
    type: WATERTEMP

  - platform: heat_curve_climate
    name: "Boiler setting"
    unit_of_measurement: "%"
    icon: mdi:gauge
    type: SETPOINT

  - platform: heat_curve_climate
    name: "Controller error"
    unit_of_measurement: "K"
    type: ERROR

  - platform: heat_curve_climate
    name: "Outdoor Temperature Difference"
    unit_of_measurement: "K"
    type: DELTA

  - platform: heat_curve_climate
    name: "Integral term"
    unit_of_measurement: "K"
    type: INTEGRAL

  - platform: heat_curve_climate
    name: "Proportionnal term"
    unit_of_measurement: "K"
    type: PROPORTIONAL

climate:
  - platform: heat_curve_climate
    id: boiler_climate
    name: ${name}
    sensor: current_temperature
    outdoor_sensor: outdoor_temperature
    default_target_temperature: 19
    output: boiler_cmd
    visual:
      min_temperature: 7
      max_temperature: 25
      temperature_step: 0.1
    control_parameters:
      slope: 1.45
      shift: 7
      kp: 5
      ki: 0.0005
    output_parameters:
      minimum_output: 0.1
      output_factor: 1.9
      output_offset: -41
      
output:
  - platform: frisquet_boiler
    pin: 5
    id: boiler_cmd
    boiler_id: 03B9

switch:
  - platform: heat_curve_climate
    name: "Heat Required"
    restore_mode: RESTORE_DEFAULT_OFF

api:
  services:
    - service: set_boiler_setpoint
      variables:
        setpoint: int
      then:
        - output.set_level:
            id: boiler_cmd
            level: !lambda 'return setpoint / 100.0;'

    - service: set_boiler_mode
      variables:
        mode: int
      then:
        - boiler.set_mode:
            id: boiler_cmd
            mode: !lambda 'return mode;'
            
    - service: set_control_parameters
      variables:
        slope: float
        shift: float
        kp: float
        ki: float
      then:
        - climate.heat_curve.set_control_parameters:
            id: boiler_climate
            slope: !lambda 'return slope;'
            shift: !lambda 'return shift;'
            kp: !lambda 'return kp;'
            ki: !lambda 'return ki;'
        - climate.heat_curve.reset_integral_term: boiler_climate
