substitutions:
  device: boiler
  name: "Frisquet Boiler"
  reboot_timeout: 14d
  update_interval: 60s
  ota_password: "86d8d705bb585eaf7a68c592a025884c"

esphome:
  name: ${device}

preferences:
  flash_write_interval: 72h

external_components:
  - source: github://philippemezzadri/frisquet-esphome
  
esp32:
  board: esp32dev
  framework:
    type: arduino

packages:
  common: !include common/common.yaml
  logger: !include common/logger.yaml
  binary_sensors: !include common/binary_sensors.yaml
  sensors: !include common/sensors.yaml
  switches: !include common/switches.yaml
  text_sensors: !include common/text_sensors.yaml

logger:
  baud_rate: 0
  level: DEBUG
  logs:
    sensor: INFO
    text_sensor: INFO
    one_wire: INFO

one_wire:
  - platform: gpio
    pin: GPIO26

sensor:
  - platform: homeassistant
    id: current_temperature
    entity_id: sensor.living_room_temperature
    unit_of_measurement: "°C"
    filters:
      - filter_out: nan
      - exponential_moving_average:
          alpha: 0.3
          send_every: 1
      - heartbeat: 60s
        
  - platform: homeassistant
    id: outdoor_temperature
    entity_id: sensor.outdoor_temperature
    unit_of_measurement: "°C"
    filters:
      - filter_out: nan
      - exponential_moving_average:
          alpha: 0.3
          send_every: 1
      - heartbeat: 60s

  - platform: dallas_temp
    address: 0xA2032131AB675C28
    name: "Boiler flow temperature"
    filters:
      - filter_out: 85.0
      
  - platform: dallas_temp
    address: 0xAB03213190136128
    name: "Boiler return temperature"
    filters:
      - filter_out: 85.0

  - platform: frisquet_boiler
    name: "Boiler temperature setting"
    unit_of_measurement: "°C"
    device_class: temperature
    type: FLOWTEMP

  - platform: frisquet_boiler
    name: "Boiler setting"
    unit_of_measurement: "%"
    icon: mdi:gauge
    type: SETPOINT

climate:
  - platform: heat_curve_climate
    id: boiler_climate
    name: ${name}
    sensor: current_temperature
    outdoor_sensor: outdoor_temperature
    default_target_temperature: 19
    output: boiler_cmd

    control_parameters:
      alt_curve: false
      slope: 1
      shift: 0
      max_error: 0.5
    
    output_parameters:
      minimum_output: 0.10
      maximum_output: 0.55
      heat_required_output: 0.10
      output_factor: 1.9
      output_offset: -41

    visual:
      min_temperature: 7
      max_temperature: 25
      temperature_step: 
        target_temperature: 0.5
        current_temperature: 0.1
      
output:
  - platform: frisquet_boiler
    id: boiler_cmd
    boiler_id: 03B9
    pin:
      number: 5
      ignore_strapping_warning: true

switch:
  - platform: frisquet_boiler
    test:
      name: Test mode
    pair:
      name: Pairing mode

  - platform: heat_curve_climate
    name: "Heat Required"

api:
  services:
    - service: set_boiler_setpoint
      variables:
        setpoint: int
      then:
        - output.set_level:
            id: boiler_cmd
            level: !lambda 'return setpoint / 100.0;'

    - service: set_boiler_mode
      variables:
        mode: int
      then:
        - boiler.set_mode:
            id: boiler_cmd
            mode: !lambda 'return mode;'
            
    - service: set_control_parameters
      variables:
        slope: float
        shift: float
        kp: float
      then:
        - climate.heat_curve.set_control_parameters:
            id: boiler_climate
            slope: !lambda 'return slope;'
            shift: !lambda 'return shift;'
            kp: !lambda 'return kp;'
        - climate.heat_curve.reset_integral_term: boiler_climate
