substitutions:
  device: boiler
  name: "Chaudière Frisquet"
  reboot_timeout: 14d
  update_interval: 60s
  ota_password: "86d8d705bb585eaf7a68c592a025884c"

esphome:
  name: ${device}

preferences:
  flash_write_interval: 72h

external_components:
  - source: components
  
esp32:
  board: esp32dev
  framework:
    type: arduino

packages:
  common: !include common/common.yaml
  binary_sensors: !include common/binary_sensors.yaml
  sensors: !include common/sensors.yaml
  switches: !include common/switches.yaml
  text_sensors: !include common/text_sensors.yaml

logger:
  baud_rate: 0
  level: DEBUG
  logs:
    sensor: INFO
    text_sensor: INFO

dallas:
  - pin: GPIO26
    
sensor:
  - platform: homeassistant
    id: current_temperature
    entity_id: sensor.aqara_salon_temperature
    unit_of_measurement: "°C"
    filters:
      - filter_out: nan
      - heartbeat: 60s
        
  - platform: homeassistant
    id: outdoor_temperature
    entity_id: sensor.outdoor_temperature
    unit_of_measurement: "°C"
    filters:
      - filter_out: nan
      - heartbeat: 60s

  - platform: dallas
    address: 0xA2032131AB675C28
    name: "Départ chaudière"

  - platform: dallas
    address: 0xAB03213190136128
    name: "Retour chaudière"

  - platform: heat_curve_climate
    name: "Consigne chaudière"
    unit_of_measurement: "°C"
    type: WATERTEMP

  - platform: heat_curve_climate
    name: "Réglage chaudière"
    unit_of_measurement: "%"
    icon: mdi:gauge
    type: SETPOINT

  - platform: heat_curve_climate
    name: "Erreur régulation"
    unit_of_measurement: "K"
    type: ERROR

  - platform: heat_curve_climate
    name: "Delta température extérieure"
    unit_of_measurement: "K"
    type: DELTA

  - platform: heat_curve_climate
    name: "Terme intégral"
    unit_of_measurement: "K"
    type: INTEGRAL

  - platform: heat_curve_climate
    name: "Terme proportionnel"
    unit_of_measurement: "K"
    type: PROPORTIONAL

climate:
  - platform: heat_curve_climate
    id: boiler_climate
    name: ${name}
    sensor: current_temperature
    outdoor_sensor: outdoor_temperature
    output: boiler_cmd
    visual:
      min_temperature: 7
      max_temperature: 25
      temperature_step: 0.1
    control_parameters:
      heat_factor: 1.65
      offset: 21.5
      kp: 5
      ki: 0
    output_parameters:
      minimum_output: 0.1
      output_factor: 1.9
      output_offset: -41
      
output:
  - platform: frisquet_boiler
    pin: 5
    id: boiler_cmd
    boiler_id: 03B9

api:
  services:
    - service: set_boiler_setpoint
      variables:
        setpoint: int
      then:
        - output.set_level:
            id: boiler_cmd
            level: !lambda 'return setpoint / 100.0;'

    - service: set_boiler_mode
      variables:
        mode: int
      then:
        - boiler.set_mode:
            id: boiler_cmd
            mode: !lambda 'return mode;'
            
    - service: set_control_parameters
      variables:
        heat_factor: float
        offset: float
        kp: float
        ki: float
      then:
        - climate.heat_curve.set_control_parameters:
            id: boiler_climate
            heat_factor: !lambda 'return heat_factor;'
            offset: !lambda 'return offset;'
            kp: !lambda 'return kp;'
            ki: !lambda 'return ki;'
