# File to be located in home assistant 'config/packages' folder.
#
input_number:
  boiler_slope:
    name: Boiler Slope
    min: 0
    max: 3
    step: 0.01
    mode: box
  boiler_shift:
    name: Boiler Shift
    min: 0
    max: 30
    step: 0.5
    mode: box
  boiler_kp:
    name: Boiler Kp
    min: 0
    max: 10
    step: 0.5
    mode: box
  boiler_ki:
    name: Boiler Ki
    min: 0
    max: 1
    step: 0.001
    mode: box

automation:
  - alias: Boiler Anti-freeze Mode
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: climate.chaudiere_frisquet
        attribute: temperature
        below: "7.2"
    condition: []
    action:
      - service: esphome.boiler_set_boiler_mode
        data:
          mode: 4
    mode: single
  - alias: Boiler Eco Mode
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: climate.chaudiere_frisquet
        attribute: temperature
        above: "7.2"
        below: "17.2"
    condition: []
    action:
      - service: esphome.boiler_set_boiler_mode
        data:
          mode: 0
    mode: single
  - alias: Boiler Confort Mode
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: climate.chaudiere_frisquet
        attribute: temperature
        above: "17"
    condition: []
    action:
      - service: esphome.boiler_set_boiler_mode
        data:
          mode: 3
    mode: single

  - alias: Boiler Set Control Parameters
    description: Set control parameters
    trigger:
      - platform: state
        entity_id:
          - input_number.boiler_slope
          - input_number.boiler_shift
          - input_number.boiler_kp
          - input_number.boiler_ki
    condition: []
    action:
      - service: esphome.boiler_set_control_parameters
        data:
          slope: "{{ states('input_number.boiler_slope') | float}}"
          shift: "{{ states('input_number.boiler_shift') | float }}"
          kp: "{{ states('input_number.boiler_kp') | float }}"
          ki: "{{ states('input_number.boiler_ki') | float }}"
    mode: restart

  - alias: Boiler Restore Control Parameters
    description: Restore control parameters after a reboot
    trigger:
      - platform: numeric_state
        entity_id: sensor.chaudiere_frisquet_uptime
        below: 60
    condition: []
    action:
      - service: esphome.boiler_set_control_parameters
        data:
          slope: "{{ states('input_number.boiler_slope') | float}}"
          shift: "{{ states('input_number.boiler_shift') | float }}"
          kp: "{{ states('input_number.boiler_kp') | float }}"
          ki: "{{ states('input_number.boiler_ki') | float }}"
      - delay: "00:01:30"
    mode: single
    max_exceeded: silent
